name: S3ssoCraft
version: '${project.version}'
main: me.gurwi.s3ssocraft.S3ssoCraft
commands:
  sessocraft:
    description: Main Command
    aliases:
      - sex
      - sexcraft
      - anal
      - analcraft
